import { defineConfig } from 'tinacms'; import RoofingCloudinaryMediaStore from './media/cloudinary-store';
const branch=process.env.GITHUB_HEAD_REF || process.env.WORKERS_CI_BRANCH || process.env.CF_PAGES_BRANCH || process.env.GITHUB_REF_NAME || 'main';
const seoFields=[{type:'string',name:'seoTitle',label:'SEO titulek'},{type:'string',name:'seoDescription',label:'SEO popis',ui:{component:'textarea'}},{type:'string',name:'canonicalUrl',label:'Kanonická URL'},{type:'image',name:'ogImage',label:'Obrázek pro sdílení'},{type:'boolean',name:'noIndex',label:'Zakázat indexaci'}] as any;
const imageMeta=(name:string,label:string)=>({type:'object',name,label,list:true,fields:[{type:'image',name:'src',label:'Obrázek'},{type:'string',name:'alt',label:'Alternativní text'},{type:'string',name:'caption',label:'Popisek'},{type:'string',name:'credit',label:'Autor / zdroj'}]});
const blockTemplates:any[]=[
{name:'hero',label:'Hlavní hero',fields:[{type:'string',name:'eyebrow',label:'Nadpis nad titulkem'},{type:'string',name:'heading',label:'Hlavní titulek'},{type:'string',name:'description',label:'Popis',ui:{component:'textarea'}},{type:'string',name:'primaryButtonLabel',label:'Primární tlačítko'},{type:'string',name:'primaryButtonUrl',label:'Odkaz primárního tlačítka'},{type:'string',name:'secondaryButtonLabel',label:'Sekundární tlačítko'},{type:'string',name:'secondaryButtonUrl',label:'Odkaz sekundárního tlačítka'},{type:'image',name:'backgroundImage',label:'Hlavní fotografie'},{type:'string',name:'proofItems',label:'Krátké důkazy / klienti',list:true}]},
{name:'trustBar',label:'Pruh důvěry',fields:[{type:'object',name:'items',label:'Položky',list:true,fields:[{type:'string',name:'value',label:'Hodnota'},{type:'string',name:'label',label:'Popis'}]}]},
{name:'problemBand',label:'Problémy zákazníka',fields:[{type:'string',name:'eyebrow',label:'Malý nadpis'},{type:'string',name:'heading',label:'Titulek'},{type:'string',name:'description',label:'Popis',ui:{component:'textarea'}},{type:'object',name:'items',label:'Položky',list:true,fields:[{type:'string',name:'title',label:'Titulek'},{type:'string',name:'body',label:'Text'},{type:'string',name:'label',label:'Text odkazu'},{type:'string',name:'url',label:'Odkaz'}]}]},
{name:'featuredProjects',label:'Vybrané realizace',fields:[{type:'string',name:'eyebrow',label:'Malý nadpis'},{type:'string',name:'heading',label:'Titulek'},{type:'string',name:'description',label:'Popis',ui:{component:'textarea'}},{type:'number',name:'limit',label:'Počet realizací'}]},
{name:'processSteps',label:'Postup / kroky',fields:[{type:'string',name:'eyebrow',label:'Malý nadpis'},{type:'string',name:'heading',label:'Titulek'},{type:'string',name:'theme',label:'Vzhled',options:[{label:'Tmavý',value:'forest'},{label:'Světlý',value:'paper'}]},{type:'object',name:'items',label:'Kroky',list:true,fields:[{type:'string',name:'title',label:'Titulek'},{type:'string',name:'body',label:'Text'}]}]},
{name:'subHero',label:'Úvod podstránky',fields:[{type:'string',name:'eyebrow',label:'Sekce'},{type:'string',name:'heading',label:'Titulek'},{type:'string',name:'description',label:'Popis',ui:{component:'textarea'}},{type:'image',name:'backgroundImage',label:'Fotografie'}]},
{name:'projectCases',label:'Seznam realizací',fields:[{type:'string',name:'displayMode',label:'Zobrazení',options:['all','featured']}]},
{name:'servicesDetail',label:'Seznam služeb',fields:[{type:'string',name:'eyebrow',label:'Malý nadpis'},{type:'string',name:'heading',label:'Titulek'},{type:'string',name:'description',label:'Popis',ui:{component:'textarea'}}]},
{name:'registryReferences',label:'Veřejné reference',fields:[{type:'number',name:'recordCount',label:'Počet záznamů v registru'},{type:'string',name:'heading',label:'Titulek'},{type:'string',name:'description',label:'Popis',ui:{component:'textarea'}}]},
{name:'companyStory',label:'O firmě',fields:[{type:'string',name:'eyebrow',label:'Malý nadpis'},{type:'string',name:'heading',label:'Titulek'},{type:'string',name:'body',label:'Text',ui:{component:'textarea'}},{type:'image',name:'image',label:'Fotografie'},{type:'string',name:'imageAlt',label:'Alternativní text'},{type:'string',name:'imageCaption',label:'Popisek fotografie'}]},
{name:'contactForm',label:'Kontaktní formulář',fields:[{type:'string',name:'heading',label:'Titulek'}]},
{name:'richText',label:'Textová sekce',fields:[{type:'string',name:'heading',label:'Titulek'},{type:'string',name:'paragraphs',label:'Odstavce',list:true,ui:{component:'textarea'}}]},
{name:'gallery',label:'Galerie',fields:[{type:'string',name:'eyebrow',label:'Malý nadpis'},{type:'string',name:'heading',label:'Titulek'},imageMeta('images','Fotografie')]},
{name:'beforeAfter',label:'Před / po',fields:[{type:'string',name:'heading',label:'Titulek'},{type:'image',name:'beforeImage',label:'Fotografie před'},{type:'string',name:'beforeAlt',label:'Alt před'},{type:'image',name:'afterImage',label:'Fotografie po'},{type:'string',name:'afterAlt',label:'Alt po'}]},
{name:'faq',label:'Časté dotazy',fields:[{type:'string',name:'heading',label:'Titulek'},{type:'object',name:'items',label:'Dotazy',list:true,fields:[{type:'string',name:'question',label:'Otázka'},{type:'string',name:'answer',label:'Odpověď',ui:{component:'textarea'}}]}]},
{name:'contactCta',label:'Kontaktní výzva',fields:[{type:'string',name:'eyebrow',label:'Malý nadpis'},{type:'string',name:'heading',label:'Titulek'},{type:'string',name:'primaryLabel',label:'Primární tlačítko'},{type:'string',name:'primaryUrl',label:'Primární odkaz'},{type:'string',name:'secondaryLabel',label:'Sekundární tlačítko'},{type:'string',name:'secondaryUrl',label:'Sekundární odkaz'}]},
{name:'spacer',label:'Mezera',fields:[{type:'number',name:'height',label:'Výška (px)'}]}];
export default defineConfig({branch,clientId:process.env.PUBLIC_TINA_CLIENT_ID||'',token:process.env.TINA_TOKEN||'',build:{outputFolder:'admin',publicFolder:'public'},media:{loadCustomStore:async()=>RoofingCloudinaryMediaStore,accept:'image/*'},ui:{previewUrl:()=>({url:process.env.SITE_URL||'http://localhost:4321'})},schema:{collections:[
{name:'page',label:'Stránky',path:'content/pages',format:'json',fields:[{type:'string',name:'title',label:'Název stránky',required:true},{type:'string',name:'slug',label:'Slug',required:true},...seoFields,{type:'object',name:'sections',label:'Sekce stránky',list:true,templates:blockTemplates}]},
{name:'project',label:'Realizace',path:'content/projects',format:'json',ui:{filename:{readonly:false,slugify:(v:any)=>v.slug}},fields:[{type:'string',name:'title',label:'Název realizace',required:true},{type:'string',name:'slug',label:'Slug',required:true},{type:'string',name:'status',label:'Stav',required:true,options:[{label:'Koncept',value:'draft'},{label:'Publikováno',value:'published'},{label:'Archiv',value:'archived'}]},{type:'string',name:'clientName',label:'Klient'},{type:'string',name:'buildingName',label:'Objekt'},{type:'string',name:'location',label:'Lokalita'},{type:'number',name:'year',label:'Rok'},{type:'datetime',name:'dateStart',label:'Začátek'},{type:'datetime',name:'dateCompleted',label:'Dokončení'},{type:'number',name:'contractValue',label:'Hodnota smlouvy'},{type:'string',name:'currency',label:'Měna',options:['CZK','EUR']},{type:'string',name:'shortDescription',label:'Krátký popis projektu',ui:{component:'textarea'}},{type:'string',name:'fullDescription',label:'Podrobný popis',ui:{component:'textarea'}},{type:'string',name:'services',label:'Služby',list:true},{type:'string',name:'projectType',label:'Typ realizace'},{type:'string',name:'buildingType',label:'Typ objektu'},{type:'image',name:'heroImage',label:'Hlavní fotografie'},{type:'string',name:'imageAlt',label:'Alternativní text hlavní fotografie'},{type:'string',name:'imageCaption',label:'Popisek / zdroj fotografie'},imageMeta('gallery','Galerie'),imageMeta('beforeImages','Fotografie před'),imageMeta('afterImages','Fotografie po'),{type:'object',name:'registryLinks',label:'Veřejné záznamy',list:true,fields:[{type:'string',name:'label',label:'Název odkazu'},{type:'string',name:'url',label:'URL'},{type:'string',name:'source',label:'Zdroj'}]},{type:'object',name:'externalLinks',label:'Další odkazy',list:true,fields:[{type:'string',name:'label',label:'Název'},{type:'string',name:'url',label:'URL'}]},{type:'boolean',name:'featured',label:'Zvýraznit na webu'},{type:'number',name:'homepagePriority',label:'Pořadí na úvodní stránce'},{type:'boolean',name:'verified',label:'Ověřené údaje'},...seoFields,{type:'datetime',name:'createdAt',label:'Vytvořeno'},{type:'datetime',name:'updatedAt',label:'Aktualizováno'}]},
{name:'service',label:'Služby',path:'content/services',format:'json',fields:[{type:'string',name:'name',label:'Název',required:true},{type:'string',name:'slug',label:'Slug',required:true},{type:'string',name:'shortDescription',label:'Krátký popis',ui:{component:'textarea'}},{type:'string',name:'description',label:'Popis',ui:{component:'textarea'}},{type:'string',name:'items',label:'Konkrétní práce',list:true},{type:'image',name:'heroImage',label:'Hlavní fotografie'},{type:'string',name:'relatedProjects',label:'Související realizace',list:true},{type:'boolean',name:'featured',label:'Zvýraznit'},{type:'number',name:'order',label:'Pořadí'},{type:'string',name:'seoTitle',label:'SEO titulek'},{type:'string',name:'seoDescription',label:'SEO popis'}]},
{name:'registryReference',label:'Reference / smluvní záznamy',path:'content/references',format:'json',fields:[{type:'string',name:'label',label:'Název',required:true},{type:'string',name:'slug',label:'Slug',required:true},{type:'number',name:'year',label:'Rok'},{type:'number',name:'amount',label:'Částka'},{type:'string',name:'currency',label:'Měna'},{type:'string',name:'url',label:'Veřejný odkaz',required:true},{type:'string',name:'source',label:'Zdroj'},{type:'number',name:'order',label:'Pořadí'},{type:'boolean',name:'verified',label:'Ověřeno'}]},
{name:'companySettings',label:'Nastavení firmy',path:'content/settings/company',format:'json',fields:[{type:'string',name:'companyName',label:'Značka'},{type:'string',name:'legalName',label:'Právní název'},{type:'string',name:'ico',label:'IČO'},{type:'string',name:'dic',label:'DIČ'},{type:'string',name:'phone',label:'Telefon'},{type:'string',name:'secondaryPhone',label:'Druhý telefon'},{type:'string',name:'email',label:'E-mail'},{type:'string',name:'address',label:'Adresa'},{type:'string',name:'serviceArea',label:'Oblast působení'},{type:'string',name:'openingHours',label:'Provozní doba'},{type:'string',name:'googleMapsUrl',label:'Google Maps URL'},{type:'string',name:'registryUrl',label:'Registr smluv URL'},{type:'string',name:'nenUrl',label:'NEN URL'},{type:'string',name:'companyDescription',label:'Popis firmy',ui:{component:'textarea'}},{type:'string',name:'founded',label:'Vznik'},{type:'string',name:'trade',label:'Obor'},{type:'string',name:'footerText',label:'Text v patičce',ui:{component:'textarea'}},{type:'string',name:'verifiedClaims',label:'Ověřená tvrzení',list:true}]},
{name:'siteSettings',label:'Nastavení webu',path:'content/settings/site',format:'json',fields:[{type:'string',name:'siteName',label:'Název webu'},{type:'string',name:'siteUrl',label:'Produkční URL'},{type:'string',name:'defaultSeoTitle',label:'Výchozí SEO titulek'},{type:'string',name:'defaultSeoDescription',label:'Výchozí SEO popis',ui:{component:'textarea'}},{type:'image',name:'logo',label:'Logo'},{type:'image',name:'favicon',label:'Favicon'},{type:'object',name:'navigation',label:'Hlavní navigace',list:true,fields:[{type:'string',name:'label',label:'Text'},{type:'string',name:'href',label:'Odkaz'}]},{type:'object',name:'footerNavigation',label:'Navigace v patičce',list:true,fields:[{type:'string',name:'label',label:'Text'},{type:'string',name:'href',label:'Odkaz'}]},{type:'string',name:'primaryCTA',label:'Hlavní CTA'},{type:'string',name:'primaryCTALink',label:'Odkaz CTA'},{type:'string',name:'analyticsId',label:'Analytics ID'}]},
{name:'testimonial',label:'Reference zákazníků',path:'content/testimonials',format:'json',fields:[{type:'string',name:'name',label:'Jméno',required:true},{type:'string',name:'company',label:'Firma / SVJ'},{type:'string',name:'role',label:'Role'},{type:'string',name:'quote',label:'Citace',ui:{component:'textarea'},required:true},{type:'string',name:'source',label:'Zdroj'},{type:'boolean',name:'verified',label:'Ověřeno'}]}
]}});
